"""add scheduled_after to jobs

Revision ID: 0574c829b686
Revises: dcc24ff2df57
Create Date: 2026-02-08 21:52:27.525734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0574c829b686'
down_revision: Union[str, None] = 'dcc24ff2df57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('scheduled_after', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'scheduled_after')
    # ### end Alembic commands ###
