"""add role policy and duration columns

Revision ID: 6a3d240d3193
Revises: 5dd104510691
Create Date: 2026-02-07 10:40:30.011702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a3d240d3193'
down_revision: Union[str, None] = '5dd104510691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('managed_policy_arns', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('roles', sa.Column('inline_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('roles', sa.Column('allowed_users', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('roles', sa.Column('api_session_duration', sa.Integer(), server_default='900', nullable=False))
    op.add_column('roles', sa.Column('console_session_duration', sa.Integer(), server_default='3600', nullable=False))
    op.drop_column('roles', 'max_session_duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('max_session_duration', sa.INTEGER(), server_default=sa.text('3600'), autoincrement=False, nullable=False))
    op.drop_column('roles', 'console_session_duration')
    op.drop_column('roles', 'api_session_duration')
    op.drop_column('roles', 'allowed_users')
    op.drop_column('roles', 'inline_policy')
    op.drop_column('roles', 'managed_policy_arns')
    # ### end Alembic commands ###
