"""add alias and color columns to accounts

Revision ID: 997a9a2fb56d
Revises: dd6da000784b
Create Date: 2026-02-09 23:33:44.402955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '997a9a2fb56d'
down_revision: Union[str, None] = 'dd6da000784b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('alias', sa.String(length=63), nullable=True))
    op.add_column('accounts', sa.Column('color', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'color')
    op.drop_column('accounts', 'alias')
    # ### end Alembic commands ###
