"""add aws_status column to accounts

Revision ID: dcc24ff2df57
Revises: 15643aa3bbce
Create Date: 2026-02-07 21:52:53.348516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc24ff2df57'
down_revision: Union[str, None] = '15643aa3bbce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('aws_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'aws_status')
    # ### end Alembic commands ###
