"""add last_used_at and preferred_username

Revision ID: dd6da000784b
Revises: a7f2c3d1e4b5
Create Date: 2026-02-09 20:38:27.728819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd6da000784b'
down_revision: Union[str, None] = 'a7f2c3d1e4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('users', sa.Column('preferred_username', sa.String(length=255), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_username')
    op.drop_column('roles', 'last_used_at')
    # ### end Alembic commands ###
